window.CNY_ICON_FILES = ["Abalone.png","Abundance.png","Ang Bao.png","Bai Nian.png","Bak Kwa.png","Cai Shen Ye.png","Calligraphy.png","Chap Chye.png","Chap Goh Mei.png","Cheongsam.png","Chinese Knot.png","Dragon Dance.png","Family.png","Firecrackers.png","Gold Ingots.png","Good Fortune.png","Happiness.png","Harmony.png","Health.png","Kueh Bangkit.png","Kumquat.png","Lion Dance.png","Lohei.png","Longevity.png","Love Letters.png","Luck.png","Mahjong.png","Mandarin Oranges.png","Melon Seeds.png","New Moon.png","Nian Gao.png","Paper Cutting.png","Peach Blossoms.png","Persimmons.png","Phoenix.png","Pineapple Tarts.png","Pineapple.png","Plum Blossoms.png","Pomelo.png","Prawn Rolls.png","Prosperity.png","Red Lanterns.png","Kueh Lapis.png","Reunion Dinner.png","Spring Cleaning.png","Steamboat.png","Steamed Fish.png","Success.png","Wealth.png","Zodiac Horse.png"];

window.CNY_ICON_DESCS = [
  ["Abalone.png", "A luxury ingredient often served at New Year feasts, symbolising wealth and success."],
  ["Abundance.png", "Fish (鱼, yú) sounds like “surplus” - the commonly wished proverb 年年有余 (nian nian you yu) means 'may you have abundance every year.'"],
  ["Ang Bao.png", "Red packets with money given as blessings for good luck, prosperity, and protection — especially to children and juniors."],
  ["Bai Nian.png", "The CNY tradition of visiting others to exchange greetings, good wishes, and snacks (lots of snacks)."],
  ["Bak Kwa.png", "Sweet barbecued pork jerky — a modern CNY favourite that signals celebration and indulgence. Halal friends can try chicken or beef bak kwa!"],
  ["Cai Shen Ye.png", "The God of Wealth (财神爷), welcomed at the start of the new year to bring financial luck and prosperity."],
  ["Calligraphy.png", "The 福 (fu, “good fortune”) character on a red diamond; often hung upside-down so “fortune arrives” — “fu dao” sounds like “fortune has come”."],
  ["Chap Chye.png", "A homestyle mixed-vegetable dish often eaten for a fresh, balanced start to the new year."],
  ["Chap Goh Mei.png", "The 15th and final day of CNY — traditionally a festive “closing” with lanterns and gatherings."],
  ["Cheongsam.png", "A traditional dress commonly worn during CNY, symbolising festive pride, elegance, and confidence."],
  ["Chinese Knot.png", "A decorative knot with no beginning or end, representing unity, longevity, and good luck."],
  ["Dragon Dance.png", "A powerful performance believed to chase away bad luck and bring strength and prosperity."],
  ["Family.png", "CNY is about reunion, respect for elders, and spending time together — even if it means awkward questions."],
  ["Firecrackers.png", "Traditionally lit to scare away evil spirits and bad luck with loud noise and bright energy."],
  ["Gold Ingots.png", "Ancient-style gold ingots used as decorations to represent wealth and financial success."],
  ["Good Fortune.png", "A general blessing for luck, smooth experiences, and good things coming your way this year."],
  ["Happiness.png", "A universal wish symbolising joy, celebration, and happy relationships."],
  ["Harmony.png", "A wish for peace and smooth relationships — especially useful during family gatherings."],
  ["Health.png", "A key New Year wish for everyone, especially elders — good health is the foundation for everything else."],
  ["Kueh Bangkit.png", "A light, crumbly coconut cookie that melts in the mouth, mildly sweet and commonly enjoyed during New Year visits."],
  ["Kumquat.png", "A “golden” fruit associated with wealth and good fortune, often displayed or gifted during CNY."],
  ["Lion Dance.png", "A lively performance believed to bring luck to homes and businesses, and scare away misfortune."],
  ["Lohei.png", "The tossing of lohei or yusheng while shouting auspicious phrases — the higher the toss, the higher the luck."],
  ["Longevity.png", "A New Year blessing for long life and strong health, often represented by traditional symbols like peaches or long noodles."],
  ["Love Letters.png", "Crispy rolled wafer biscuits — a sweet snack for visiting and sharing."],
  ["Luck.png", "Simple and universal: a wish for good outcomes, good timing, and fewer bad surprises this year."],
  ["Mahjong.png", "A traditional game often played during CNY, symbolising bonding, strategy, and friendly competition."],
  ["Mandarin Oranges.png", "Gifted in pairs as a symbol of luck and wealth — a classic CNY greeting in fruit form."],
  ["Melon Seeds.png", "A classic CNY snack for nibbling and sharing, linked with abundance and family blessings."],
  ["New Moon.png", "The new moon marks the start of the lunar calendar and the official beginning of the new year."],
  ["Nian Gao.png", "Sticky rice cake whose name sounds like “higher year”, symbolising growth, promotion, and improvement."],
  ["Paper Cutting.png", "Red paper decorations featuring auspicious symbols, traditionally handmade for festive luck."],
  ["Peach Blossoms.png", "A popular symbol for romance and new relationships — especially for singles."],
  ["Persimmons.png", "A fruit associated with things going smoothly and good outcomes unfolding as planned."],
  ["Phoenix.png", "A mythical bird symbolising renewal, grace, and prosperity — often paired with the dragon."],
  ["Pineapple Tarts.png", "A CNY staple in Singapore; pineapple (Hokkien: ong lai) sounds like “fortune arrives.”"],
  ["Pineapple.png", "Pineapple in Hokkien is “ong lai” meaning “fortune arrives”, a symbol of prosperity also commonly rolled by new BTO residents."],
  ["Plum Blossoms.png", "A winter bloom symbolising resilience, renewal, and hope — thriving even in tough seasons."],
  ["Pomelo.png", "A large citrus fruit associated with abundance, good fortune, and family togetherness."],
  ["Prawn Rolls.png", "Crispy snack rolls served during visits — a festive favourite for sharing and celebrating."],
  ["Prosperity.png", "The “zhao cai mao” or prosperity cat is often seen as a good-luck charm for wealth, business success, and money flowing in."],
  ["Red Lanterns.png", "Bright red lanterns symbolising joy, celebration, and a “bright” new year ahead."],
  ["Kueh Lapis.png", "A rich, layered festive cake that's commonly served for CNY as well as other festive Singaporean occasions."],
  ["Reunion Dinner.png", "The most important meal of CNY, bringing families together on New Year's Eve."],
  ["Spring Cleaning.png", "Cleaning before CNY to sweep away bad luck and make space for good fortune."],
  ["Steamboat.png", "A communal hotpot meal symbolising warmth, togetherness, and shared prosperity."],
  ["Steamed Fish.png", "A must-have New Year dish because fish (鱼, yú) sounds like “surplus” representing abundance and prosperity."],
  ["Success.png", "A wish for achievements, promotions, and personal breakthroughs in the new year."],
  ["Wealth.png", "A blessing for financial prosperity and stability — often represented by gold, coins, and lucky symbols."],
  ["Zodiac Horse.png", "The Horse zodiac represents energy, momentum, and progress — a sign of moving forward strongly."],
];

window.CNY_ICON_DESC_MAP = Object.fromEntries(window.CNY_ICON_DESCS);